[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "sbilifeco-presenter-html-non-sql-answers"
version = "0.1.2"
description = "Non-SQL answers presented as an HTML page"
dependencies = [
    "jinja2>=3.1.6",
    "sbilifeco-boundary-non-sql-notify-flow>=0.1.0",
    "sbilifeco-boundary-query-flow>=0.2.0",
]