[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "sbilifeco-flow-non-sql-notify"
version = "0.1.1"
description = "Flow to fetch non-SQL answers and notify about them to presenters"
dependencies = [
    "sbilifeco-boundary-non-sql-notify-flow>=0.1.0",
    "sbilifeco-boundary-query-flow>=0.2.0"
]