[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "sbilifeco-boundary-metadata-storage"
version = "0.1.5"
description = "Contract for metadata storage"
dependencies = [
    "sbilifeco-models-base>=0.1.3",
    "sbilifeco-models-db-metadata>=0.1.6"
]
