[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "sbilifeco-kafka-producer-query-flow-events"
version = "0.1.1"
description = "Kafka producer that relays events produced by query flow as kafka messages"
dependencies = [
    "sbilifeco-models-base>=0.1.3",
    "sbilifeco-cp-kafka>=0.2.1",
    "sbilifeco-boundary-query-flow>=0.1.9",
    "sbilifeco-paths-query-flow>=0.1.6"
]